CREATE TABLE PM_SENSORS (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    lon FLOAT NOT NULL,
    lat FLOAT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PRECIPITATION (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    tstamp VARCHAR(255) NOT NULL,
    duration INTEGER NOT NULL,
    mm FLOAT NOT NULL,
    raining INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE WIND (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    tstamp VARCHAR(255) NOT NULL,
    speed FLOAT NOT NULL,
    degree INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PM_VALUES (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    time_stamp VARCHAR(255) NOT NULL,
    P1 FLOAT NOT NULL,
    P2 FLOAT NOT NULL,
    PRIMARY KEY (id, time_stamp)
);